### ISSUE TITLE
How can I contribute a chinese version? 

### ISSUE THREAD

**Issue by ldwformat** [learning-rust/learning-rust.github.io#20]
Hi,
I am a developer who is learning the Rust recently. I've read some books about Rust, and I feel this site is a good tool. I noticed that there is a language switcher at the top of the page, but English is the only option, for now.

I want to add a Chinese version of these docs and I need to know how can I do that :)

**Comment by dumindu** [comment]
Hi,
I am using [Hexo nodejs framework](https://hexo.io/) for the site and the documentation you are searching is https://hexo.io/docs/internationalization :)

Also you can refer [the code of Hexo's doc project](https://github.com/hexojs/site/tree/master/source) to see, how they have do that.

**Comment by ldwformat** [comment]
Ok, I'll try that. Thx~
