### ISSUE TITLE
Text improvements to "Rust Basics"

### ISSUE THREAD

**Issue by thomasaarholt** [learning-rust/learning-rust.github.io#25]
Rust beginner here, coming from Python.

I'm noticing some parts of the text that either have some language errors or could do with clarification. Since my main intention today is to learn some Rust, I'm not creating PRs to fix them all now, but instead gathering them here and then either I or maybe someone else can go through them later.

Updating as I go:

- [Basics -> Cargo](https://learning-rust.github.io/docs/a4.cargo,crates_and_basic_project_structure.html): "But mainly it uses for," is an odd rather empty sentence. The following bullet points don't really fit in with the idea of a package manager either. I'm familiar with package managers that let me download and install software others have written (i.e. matplotlib). This section appears to be concerned with creating projects to share with others? Maybe that should be moved to after the reader has downloaded some packages?

- [Basics -> Comments](https://learning-rust.github.io/docs/a5.comments_and_documenting_the_code.html): "*Never use block comments*" does not teach me why not. What is the difference between module and crate level documentation? Maybe move the latter discussion to later rather than confuse now?

**Comment by dumindu** [comment]
Hi Thomas,
Thanks for your feedback and really appreciate it.

First case I want to tell, cargo is more than a package manager. And we can
install binaries via cargo install. I'll check on this case and will update
that part.

Second case; have to check. Don't remember the exact reason now.

You can add suggestions here in point form or email me to
dumindumr[at]gmail or chat on Reddit u/dumindunuwan. I can't promise that I
can check and fix them very soon. But I will work on them when I got a free
time for sure and suggestions are very welcome.

Same time, you can use https://gitter.im/rust-lang/rust or official Rust
IRC to get quick answers for your questions :)

**Comment by dumindu** [comment]
I was mainly worked on new section about error handling past months. Will check this within this month :)

**Comment by dumindu** [comment]
Hi @thomasaarholt ,
Sorry for the late response. Thanks for creating this issue. I made some changes on [Basics -> Cargo](https://learning-rust.github.io/docs/a4.cargo,crates_and_basic_project_structure.html). I think it's more cleaner now. 
About comments; Those are sort of conventions and can be seen in https://doc.rust-lang.org/1.0.0/style/style/comments.html and https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/guide.md partially.

And thanks again for reporting these :)
