### ISSUE TITLE
Consider rewording of comparable language reference for interface trait comparison

### ISSUE THREAD

**Issue by softprops** [learning-rust/learning-rust.github.io#3]
Referencing Java interfaces as a comparison to traits then right after making a "but" traits can have default method impls may cause some confusion for Java developers https://github.com/learning-rust/site/blob/master/source/docs/b5.impls_and_traits.md

The reason being that Java interfaces can also have default method impls https://docs.oracle.com/javase/tutorial/java/IandI/defaultmethods.html. 

I'm suggesting the change because I'm offering this content up to my company of mostly Java/Scala developers as onboarding material for learning rust.

**Comment by dumindu** [comment]
acknowledged! Let me check on this weekend. 
Thanks

**Comment by softprops** [comment]
Awesome. There are some other areas I though could use some small improvement s. Are you open to pull requests?

**Comment by dumindu** [comment]
Hi,
> Are you open to pull requests?

Yes, as long as you can keep the simplicity of the docs. And please make sure to write things on simplest and shortest way. Also try to target whole audience especially newcomers to programming.

Thanks

**Comment by dumindu** [comment]
I made a [small change](https://github.com/learning-rust/site/commit/e6148535713e413153f177bd81ef8db8d240fb72) on [Impls & Traits](https://learning-rust.github.io/docs/b5.impls_and_traits.html). @softprops can you check it?

Also feel free to create PRs and please let me know if you got any feedback from your developers how I can improve this doc further. Thanks

**Comment by softprops** [comment]
That works. One grammatical note

> Multiple traits can be implemented to a single type.

Should probably read

> Multiple traits can be implemented for a single type.

**Comment by dumindu** [comment]
Updated! Thanks
