### ISSUE TITLE
Hi I was just visiting your website

### ISSUE THREAD

**Issue by Kipung** [learning-rust/learning-rust.github.io#3]
Hi! I was just visiting your website and saw "guilds" in your a1.whyrust?(I am not sure about the exact html file name) Doc at the bottom i believe. I am just a beginning rust learner who basically freshly setup a rust environment. I wasn't sure whether "guilds" are actual thing or not in rust but if not I think you meant "guides" right? 

And I thought your website was cool!

**Comment by dumindu** [comment]
Hi @Kipung,
Thanks for reporting typo issue. I'll fix upcoming days.
Enjoy the weekend.

**Comment by dumindu** [comment]
@Kipung Updated https://github.com/learning-rust/site/commit/ff9bc23f283e23a4ed464c29d01dac5b584f43f7
Thanks for reporting!
