### ISSUE TITLE
Primitive Data Types: reference to IEEE floating-point standard in integers section

### ISSUE THREAD

**Issue by demin-dmitriy** [learning-rust/learning-rust.github.io#32]
I'm confused

* In section "i8, i16, i32, i64, i128":
    > Min and max values are based on IEEE standard for Binary Floating-Point Arithmetic.

* In section "u8, u16, u32, u64, u128":
    > Same as signed numbers, min and max values are based on IEEE standard for Binary Floating-Point Arithmetic.

Does "IEEE standard for Binary Floating-Point Arithmetic" means IEEE 754? I think it doesn't specify integer numbers. It even says in section "2. Definitions, abbreviations, and acronyms ":
> 2.1.32 integer format: A format **not defined** in this standard that represents a subset of the integers and perhaps additional values representing infinities, NaNs, or negative zeros.

**Comment by dumindu** [comment]
Hi @demin-dmitriy,
Thanks for reporting this. Looks like I misunderstood this in my early days of Rust, https://www.reddit.com/r/rust/comments/3p1vgg/ranges_for_integer_data_types/ . 
Will update in this weekend :)

PS. Sorry, Will update within this month.

**Comment by dumindu** [comment]
@demin-dmitriy Sorry for took more time to fix it. Thanks again for reporting this.
