### ISSUE TITLE
No issues. I just want to say thank you for making this. 

### ISSUE THREAD

**Issue by mithi** [learning-rust/learning-rust.github.io#33]
Hi, I have no issues as of the moment but I just wanted to say thank you for making this. It's a really valuable resource. Maybe in the future, I'll have something to contribute. Anyway I just wanted to know that what you made is really valuable. Thank you.

**Comment by dumindu** [comment]
Hi Mithi,
The appreciations are really rare in my life. So, thank you and glad this helps for you :)
Have a nice weekend!
