### ISSUE TITLE
Maybe a misspell?

### ISSUE THREAD

**Issue by ldwformat** [learning-rust/learning-rust.github.io#34]
There is a confusing expression in the lower half of the section [about vector](https://github.com/learning-rust/site/blob/master/source/docs/b1.vectors.md), "No of elements". What does the sentence mean? "Num of the elements" ?

**Comment by dumindu** [comment]
Consider as "Number of the elements", will update later.

**Comment by TomasHubelbauer** [comment]
@ldwformat check out https://en.wikipedia.org/wiki/Numero_sign
