### ISSUE TITLE
camelCase is wrongly represented as CamelCame

### ISSUE THREAD

**Issue by guibirow** [learning-rust/learning-rust.github.io#44]
In the guides, 
You mistakenly suggest throughout the pages that things should be named using CamelCase notation. 

But it is wrongly represented, the correct names should be:

**camelCase**: lower case for first word, Capital for initial of following words.
**PascalCase**: Initial for all words should be uppercase.
**snake_case**: compound word separated by underscore

Despite that, the docs are really good, thanks to put it together.

**Comment by dumindu** [comment]
Thanks for reporting the issue and feedback. Will check and update in this weekend.
