### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by 0xcpu** [learning-rust/learning-rust.github.io#6]
I guess that in the binding of variable `d` in [arrays](https://github.com/learning-rust/site/blob/master/source/docs/a8.primitive_data_types.md#arrays) you wanted to use `=` instead of `:`. As of `Rust 1.23.0` this is an error.

**Comment by dumindu** [comment]
@cpu-00 Thanks for reporting, [fixed!](https://github.com/learning-rust/site/commit/f89e694df047470d24d92af5ab571dbbe2e2cad1)
