### ISSUE TITLE
Site CSS makes it less usable on ultrawide monitors

### ISSUE THREAD

**Issue by EthanStandel** [learning-rust/learning-rust.github.io#62]
Hey, great resource you have here! But there's some weird stuff done in the CSS that makes things go absolutely goofy on ultrawide monitors.

It looks like the developer tested the styles for ultrawide monitors like this.

![image](https://user-images.githubusercontent.com/16840301/196078007-da8f0b47-1bb1-40d5-b8ff-448e389a0f8e.png)

And that seems fine, but when that's actually _on my monitor,_ it looks like this.

![image](https://user-images.githubusercontent.com/16840301/196078100-ce25b530-1447-4acb-b20b-e45335e4282f.png)

The font size that is in my URL bar, or in the dev tools, or on the tab are perfectly optimal for reading.

I actually have to shrink the screen to make it readable, like this.

![image](https://user-images.githubusercontent.com/16840301/196078344-1457fa15-0db3-4405-81ce-07a74444c79c.png)

It looks like the problem is [this file](https://github.com/learning-rust/site/blob/9facac662136025fb4cb18eb4dc8ceec8249e5a6/themes/navy/source/css/_partial/zoom.styl). Removing that and the reference [here](https://github.com/learning-rust/site/blob/9facac662136025fb4cb18eb4dc8ceec8249e5a6/themes/navy/source/css/navy.styl#L13) would fix the problem. I really think that users can be trusted to adjust their scaling to what's comfortable to them.

**Comment by EthanStandel** [comment]
Correction, Github sent me the wrong way due to it not getting along with Git submodule.

So I guess the fix actually needs to be implemented in the docura/docura repo. However, I'll leave this here because once that is fixed, this submodule hash will need to be updated... I think.

**Comment by dumindu** [comment]
Refer https://github.com/docura/docura/issues/1#issuecomment-1281148608
Fixed in https://github.com/docura/docura/issues/1
