### ISSUE TITLE
Responsive issue on wide screen

### ISSUE THREAD

**Issue by Elliot67** [learning-rust/learning-rust.github.io#67]
There is some responsive issue when the window is larger than 2560px.
If you don't have a wide screen, you can debug that with the "simulator mode" at 50% scale.

https://github.com/learning-rust/learning-rust.github.io/assets/45725915/31c2d408-1c8c-4ace-95de-a0be628e1376

**Comment by dumindu** [comment]
Thanks for reporting this. Last time I tested mostly on Safari and Firefox. Surprisingly, no issue on Safari and Firefox even now, even with zoom on FF. Also, it looks like css zoom implementation on Safari and Chrome quite buggy(ex: list items line height) as [FF devs tells](https://www.reddit.com/r/firefox/comments/wkuvmk/will_mozilla_support_css_zoom_in_future/).

💡 Test page: https://learning-rust.github.io/docs/why-rust/

**Safari**
![Screenshot 2023-11-27 at 10 05 55 PM-min](https://github.com/learning-rust/learning-rust.github.io/assets/1280428/998b509d-2b98-4e36-8257-c4e83dbc003e)

**Firefox**
![Screenshot 2023-11-27 at 10 07 49 PM-min](https://github.com/learning-rust/learning-rust.github.io/assets/1280428/376247dd-4fa0-4f46-be62-b40ba7d8f2d6)

**Chrome** 🐛
QUD
![Screenshot 2023-11-27 at 10 06 05 PM-min](https://github.com/learning-rust/learning-rust.github.io/assets/1280428/9f3b0845-65da-4178-ade6-4edfbb80a2e8)
UHD
![Screenshot 2023-11-27 at 10 06 26 PM-min](https://github.com/learning-rust/learning-rust.github.io/assets/1280428/04096f88-ccab-413e-ac42-f6a9f0dcc16a)

![Screenshot 2023-11-27 at 10 12 21 PM](https://github.com/learning-rust/learning-rust.github.io/assets/1280428/b45f47c7-449d-4b0f-95b9-f244bdc22607)

Let me check about what's the issue first.

**Comment by dumindu** [comment]
@Elliot67 I removed `@media(min-width:2560px){body{zoom:1.2}}@media(min-width:3840px){body{zoom:1.6}}`. It looks this issue also linked with the browser's malfunctioning zoom implementation. Kindly help me to verify. Thanks

**Comment by Elliot67** [comment]
@dumindu Yep, the sidebar size is correct now :)

Didn't know about the `zoom` property, but it doesn't look like a property anyone would want.
