### ISSUE TITLE
Translation to PT/BR

### ISSUE THREAD

**Issue by c4p1t4n** [learning-rust/learning-rust.github.io#72]
I'm excited about translating the documents into pt/br. This project helped me a lot on my journey to learn about rust. How can I do this. Is it just opening a PR with the translated documents?

**Comment by dumindu** [comment]
Dear Léo,
- I'm glad to hear that this is helping you with your journey through Rust and I really appreciate your interest about adding translations for this. 
- Personally, 2017-2019 was quite tough time to me. Plus not a fan of Rust 2018 Edition (some changes added + the way they added). Examples 😁
  - https://www.reddit.com/r/rust/comments/a42gti/concerning_the_new_website_design/
  - https://medium.com/@dumindu/pushing-rust-to-2019-9616d82172d3
  - https://github.com/rust-lang/rust/issues/37854 : was blocking for 6+ years
  - https://github.com/rust-lang/api-guidelines/discussions/29
Plus with career life I had to focus more on Golang, Kubernetes, DevOps than Rust. Still can't allocate time to check all sections but already initiated. So, this is not a good time to add new translations 🙂
