### ISSUE TITLE
Confusing isize/usize description

### ISSUE THREAD

**Issue by dkm** [learning-rust/learning-rust.github.io#9]
I'm not sure to understand exactly what this means :

> Simply this is the data type to cover all unsigned integer types but memory allocates according to the
> size of a pointer. Min and max values are similar to u64.

I guess these types are similar to C's `[s]size_t`  used for storing objects size (usually 32bits on 32bits platform and 64bits on 64bits platforms).

**Comment by dumindu** [comment]
wan't fix

**Comment by dumindu** [comment]
@dkm sorry for misunderstood your above comment, especially because of I have no experience with C. But I got your point now and will add a fix for this.
Thanks

**Comment by dumindu** [comment]
I was mainly worked on new section about error handling past months. Will check this within this month :)

**Comment by dumindu** [comment]
@dkm Thanks for reporting this issue and so sorry to take a long time to fix this.
